services:

  expense-tracker:
    image: mongo:7
    container_name: mongodb-container
    restart: always

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

    volumes:
      - mongo-db:/data/db

    networks:
      - etrack-network

    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' localhost:27017/test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

#=======================================================

  backend:
    image: bhagyajeet/expense-tracker-backend-ci-ga:latest

    container_name: backend-container

    ports:
      - "5000:5000"

    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

    depends_on:
      expense-tracker:
        condition: service_healthy

    networks:
      - etrack-network

#========================================================


  frontend:
    image: bhagyajeet/expense-tracker-frontend-ci-ga:latest

    container_name: frontend-container

    ports:
      - "4173:4173"

    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

    depends_on:
      - backend

    networks:
      - etrack-network


volumes:
  mongo-db:


networks:
  etrack-network:
